### ISSUE TITLE
Failed to install from repository

### ISSUE THREAD

**Issue by pablorq** [scottbedard/oc-debugbar-plugin#32]
I'm using Ubuntu with Docker to work with OctoberCMS, using [this image](https://hub.docker.com/r/aspendigital/octobercms).

After create the container I follow the steps on the [Readme](https://github.com/rainlab/debugbar-plugin/blob/master/README.md) with the following result:

```
$ sudo docker exec octobercms_web_1 composer update
    1/13:	http://repo.packagist.org/p/provider-archived$5c1908fde45bc1e079038576bffd87719ff95f6527dee583897cd4b324d9fe1e.json
    2/13:	http://repo.packagist.org/p/provider-2020-04$ef737c3de718fa98deb29654a0c52ea9b180e4fdf4a25ba22f292dae8b2f22c1.json
    3/13:	http://repo.packagist.org/p/provider-2019-10$7568d1c39206f33251365b82b7134f502ffee570631941c9cb775f259603aab5.json
    4/13:	http://repo.packagist.org/p/provider-latest$548015ce5ac59f6ec7c2a8bf982782ac3226e5d2fe33ca56e23a7a791d86dd71.json
    5/13:	http://repo.packagist.org/p/provider-2019-07$e59eba9f1a57e928f08e2409d9a543a937531c13ec7317ad86a20a2d3546f9e1.json
    6/13:	http://repo.packagist.org/p/provider-2016$49676b5257a094cd2052e0c0ba81cd4d66464f7dad1eb120889fcf2ba6511093.json
    7/13:	http://repo.packagist.org/p/provider-2020-01$bc44ec901584f77b837f47a12c3d7c464cb70543b3d92b9fea822b234afda790.json
    8/13:	http://repo.packagist.org/p/provider-2019$e43f35fefb76a3b0aa71f888106a4809121ec49d20c3db9c672cd56705a4c463.json
    9/13:	http://repo.packagist.org/p/provider-2015$d92c2535980f04ed2ca88296ab4ea9c8101e7b46250d8ac95e09435da2095676.json
    10/13:	http://repo.packagist.org/p/provider-2014$c8b3b14ed88b7d84e62d615be1c1d7527b14183d339941da66717adeebb5037e.json
    11/13:	http://repo.packagist.org/p/provider-2017$8798d76d15734215ece6ed74ca73a0ee812d1d911561ea84457e769e67ef8d1f.json
    12/13:	http://repo.packagist.org/p/provider-2013$8f2b738de0bff98323c1b7190f9b4aafa7ef7830c32b90e89c20ada893fed5b0.json
    13/13:	http://repo.packagist.org/p/provider-2018$7c4045a8b768ddf2107bacc914a63b1f78f1b70fead48660d761959ade04f1b3.json
    Finished: success: 13, skipped: 0, failure: 0, total: 13
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wikimedia/composer-merge-plugin dev-master requires php >=7.2.0 -> your PHP version (7.2.27) overridden by "config.platform.php" version (7.0.8) does not satisfy that requirement.
    - wikimedia/composer-merge-plugin dev-master requires php >=7.2.0 -> your PHP version (7.2.27) overridden by "config.platform.php" version (7.0.8) does not satisfy that requirement.
    - Installation request for wikimedia/composer-merge-plugin dev-master -> satisfiable by wikimedia/composer-merge-plugin[dev-master].

$ sudo docker exec octobercms_web_1 composer require rainlab/debugbar
    1/3:	http://repo.packagist.org/p/provider-latest$191746a3b21d50c2b808e2afcc46556f831af144ab5f6dac88b039ffb1fcc4c8.json
    2/3:	http://repo.packagist.org/p/provider-2018$d0dc2ad3b6ecdcca7d195a7122b7bbf690456254e11056eec89b3b3161059c1e.json
    3/3:	http://repo.packagist.org/p/provider-2020-01$13971cb365a1914b43bec6da67cdf76888fd35258a73c6fb06b972a37d5c4930.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Using version ^3.0 for rainlab/debugbar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/3:	https://codeload.github.com/rainlab/debugbar-plugin/legacy.zip/a37499b3ac8749c026ccef5aca176faae7b13f13
    2/3:	https://codeload.github.com/barryvdh/laravel-debugbar/legacy.zip/67ced7c6a7451b8bb079d92a57d75f1111f3342d
    3/3:	https://codeload.github.com/maximebf/php-debugbar/legacy.zip/6c4277f6117e4864966c9cb58fb835cee8c74a1e
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Package operations: 3 installs, 0 updates, 0 removals
  - Installing maximebf/debugbar (v1.15.1): Loading from cache
  - Installing barryvdh/laravel-debugbar (v3.3.1): Loading from cache
  - Installing rainlab/debugbar (3.0.0): Loading from cache
maximebf/debugbar suggests installing predis/predis (Redis storage)
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package jakub-onderka/php-parallel-lint is abandoned, you should avoid using it. Use php-parallel-lint/php-parallel-lint instead.
Package leafo/scssphp is abandoned, you should avoid using it. Use scssphp/scssphp instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> php artisan october:util set build
-
*** October sets build: 465
-
Ping? Pong!
-
Ping? Pong!
-
> php artisan package:discover
Discovered Package: jenssegers/date
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Package manifest generated successfully.

```

As a result OctoberCMS is broken: nothing is shown on the frontend nor the backend, just a blank page.

The log from the container shows:
```
[Thu Apr 16 13:11:48.691816 2020] [php7:error] [pid 20] [client 172.20.0.1:42846] PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:752\nStack trace:\n#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('view')\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('view')\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('view', Array)\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('view', Array)\n#4 /var/www/html/vendor/october/rain/src/Foundation/Application.php(158): Illuminate\\Foundation\\Application->make('view')\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): October\\Rain\\Foundation\\Application->make('view', Array)\n#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundat in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752
[Thu Apr 16 13:11:48.692776 2020] [php7:error] [pid 20] [client 172.20.0.1:42846] PHP Fatal error:  Uncaught ReflectionException: Class view does not exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:752\nStack trace:\n#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('view')\n#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('view')\n#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('view', Array)\n#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('view', Array)\n#4 /var/www/html/vendor/october/rain/src/Foundation/Application.php(158): Illuminate\\Foundation\\Application->make('view')\n#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): October\\Rain\\Foundation\\Application->make('view', Array)\n#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundat in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752
172.20.0.1 - - [16/Apr/2020:13:11:48 +0200] "GET / HTTP/1.1" 500 211 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
```

Any idea?

**Comment by LukeTowers** [comment]
That's an issue for the docker container repo, either remove the platform requirement from your composer.json or change the wikimedia merge plugin to require 1.4.1 instead of dev-master.
