### ISSUE TITLE
issues with debugAjax = true

### ISSUE THREAD

**Issue by rajakhoury** [scottbedard/oc-debugbar-plugin#44]
Here is the exception log file when I set the `'debugAjax' => true`

`````
[2021-01-30 18:36:04] local.ERROR: ReflectionException: Class debugbar does not exist in E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php:803
Stack trace:
#0 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(803): ReflectionClass->__construct('debugbar')
#1 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): Illuminate\Container\Container->build('debugbar')
#2 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(785): Illuminate\Container\Container->resolve('debugbar', Array, true)
#3 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Foundation\Application->resolve('debugbar', Array)
#4 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(770): Illuminate\Container\Container->make('debugbar', Array)
#5 E:\www\test\vendor\october\rain\src\Foundation\Application.php(293): Illuminate\Foundation\Application->make('debugbar')
#6 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(1245): October\Rain\Foundation\Application->make('debugbar')
#7 E:\www\test\plugins\rainlab\debugbar\middleware\InterpretsAjaxExceptions.php(42): Illuminate\Container\Container->offsetGet('debugbar')
#8 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): RainLab\Debugbar\Middleware\InterpretsAjaxExceptions->handle(Object(Illuminate\Http\Request), Object(Closure))
#9 E:\www\test\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#14 E:\www\test\index.php(45): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#15 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [debugbar] does not exist. in E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
Stack trace:
#0 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): Illuminate\Container\Container->build('debugbar')
#1 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(785): Illuminate\Container\Container->resolve('debugbar', Array, true)
#2 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Foundation\Application->resolve('debugbar', Array)
#3 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(770): Illuminate\Container\Container->make('debugbar', Array)
#4 E:\www\test\vendor\october\rain\src\Foundation\Application.php(293): Illuminate\Foundation\Application->make('debugbar')
#5 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(1245): October\Rain\Foundation\Application->make('debugbar')
#6 E:\www\test\plugins\rainlab\debugbar\middleware\InterpretsAjaxExceptions.php(42): Illuminate\Container\Container->offsetGet('debugbar')
#7 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): RainLab\Debugbar\Middleware\InterpretsAjaxExceptions->handle(Object(Illuminate\Http\Request), Object(Closure))
#8 E:\www\test\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#13 E:\www\test\index.php(45): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#14 {main}  
[2021-01-30 18:36:04] local.ERROR: ReflectionException: Class path.public does not exist in E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php:803
Stack trace:
#0 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(803): ReflectionClass->__construct('path.public')
#1 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): Illuminate\Container\Container->build('path.public')
#2 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(785): Illuminate\Container\Container->resolve('path.public', Array, true)
#3 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Foundation\Application->resolve('path.public', Array)
#4 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(770): Illuminate\Container\Container->make('path.public', Array)
#5 E:\www\test\vendor\october\rain\src\Foundation\Application.php(293): Illuminate\Foundation\Application->make('path.public')
#6 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(629): October\Rain\Foundation\Application->make('path.public')
#7 E:\www\test\vendor\october\rain\src\Filesystem\Filesystem.php(99): public_path()
#8 E:\www\test\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): October\Rain\Filesystem\Filesystem->localToPublic('E:\\www\\test\\...')
#9 E:\www\test\vendor\october\rain\src\Exception\ExceptionBase.php(233): Illuminate\Support\Facades\Facade::__callStatic('localToPublic', Array)
#10 E:\www\test\modules\system\views\exception.php(49): October\Rain\Exception\ExceptionBase->getCallStack()
#11 E:\www\test\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('E:\\www\\test\\...')
#12 E:\www\test\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(21): Illuminate\View\Engines\PhpEngine->evaluatePath('E:\\www\\test/...', Array)
#13 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\PhpEngine->get('E:\\www\\test/...', Array)
#14 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#15 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#16 E:\www\test\vendor\laravel\framework\src\Illuminate\Http\Response.php(42): Illuminate\View\View->render()
#17 E:\www\test\vendor\symfony\http-foundation\Response.php(205): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#18 E:\www\test\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(55): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#19 E:\www\test\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500)
#20 E:\www\test\vendor\october\rain\src\Foundation\Exception\Handler.php(107): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#21 E:\www\test\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(51): October\Rain\Foundation\Exception\Handler->render(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#22 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(176): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#23 E:\www\test\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 E:\www\test\index.php(45): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#29 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [path.public] does not exist. in E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
Stack trace:
#0 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): Illuminate\Container\Container->build('path.public')
#1 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(785): Illuminate\Container\Container->resolve('path.public', Array, true)
#2 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Foundation\Application->resolve('path.public', Array)
#3 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(770): Illuminate\Container\Container->make('path.public', Array)
#4 E:\www\test\vendor\october\rain\src\Foundation\Application.php(293): Illuminate\Foundation\Application->make('path.public')
#5 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(629): October\Rain\Foundation\Application->make('path.public')
#6 E:\www\test\vendor\october\rain\src\Filesystem\Filesystem.php(99): public_path()
#7 E:\www\test\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): October\Rain\Filesystem\Filesystem->localToPublic('E:\\www\\test\\...')
#8 E:\www\test\vendor\october\rain\src\Exception\ExceptionBase.php(233): Illuminate\Support\Facades\Facade::__callStatic('localToPublic', Array)
#9 E:\www\test\modules\system\views\exception.php(49): October\Rain\Exception\ExceptionBase->getCallStack()
#10 E:\www\test\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('E:\\www\\test\\...')
#11 E:\www\test\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(21): Illuminate\View\Engines\PhpEngine->evaluatePath('E:\\www\\test/...', Array)
#12 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\PhpEngine->get('E:\\www\\test/...', Array)
#13 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#14 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#15 E:\www\test\vendor\laravel\framework\src\Illuminate\Http\Response.php(42): Illuminate\View\View->render()
#16 E:\www\test\vendor\symfony\http-foundation\Response.php(205): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#17 E:\www\test\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(55): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#18 E:\www\test\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500)
#19 E:\www\test\vendor\october\rain\src\Foundation\Exception\Handler.php(107): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#20 E:\www\test\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(51): October\Rain\Foundation\Exception\Handler->render(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#21 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(176): Illuminate\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#22 E:\www\test\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#27 E:\www\test\index.php(45): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#28 {main}  
[2021-01-30 18:36:04] local.ERROR: ReflectionException: Class path.public does not exist in E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php:803
Stack trace:
#0 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(803): ReflectionClass->__construct('path.public')
#1 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): Illuminate\Container\Container->build('path.public')
#2 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(785): Illuminate\Container\Container->resolve('path.public', Array, true)
#3 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Foundation\Application->resolve('path.public', Array)
#4 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(770): Illuminate\Container\Container->make('path.public', Array)
#5 E:\www\test\vendor\october\rain\src\Foundation\Application.php(293): Illuminate\Foundation\Application->make('path.public')
#6 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(629): October\Rain\Foundation\Application->make('path.public')
#7 E:\www\test\vendor\october\rain\src\Filesystem\Filesystem.php(99): public_path()
#8 E:\www\test\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): October\Rain\Filesystem\Filesystem->localToPublic('E:\\www\\test\\...')
#9 E:\www\test\vendor\october\rain\src\Exception\ExceptionBase.php(233): Illuminate\Support\Facades\Facade::__callStatic('localToPublic', Array)
#10 E:\www\test\modules\system\views\exception.php(49): October\Rain\Exception\ExceptionBase->getCallStack()
#11 E:\www\test\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('E:\\www\\test\\...')
#12 E:\www\test\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(21): Illuminate\View\Engines\PhpEngine->evaluatePath('E:\\www\\test/...', Array)
#13 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\PhpEngine->get('E:\\www\\test/...', Array)
#14 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#15 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#16 E:\www\test\vendor\laravel\framework\src\Illuminate\Http\Response.php(42): Illuminate\View\View->render()
#17 E:\www\test\vendor\symfony\http-foundation\Response.php(205): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#18 E:\www\test\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(55): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#19 E:\www\test\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500)
#20 E:\www\test\vendor\october\rain\src\Foundation\Exception\Handler.php(107): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#21 E:\www\test\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(101): October\Rain\Foundation\Exception\Handler->render(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#22 E:\www\test\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(69): Barryvdh\Debugbar\Middleware\InjectDebugbar->handleException(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#23 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#27 E:\www\test\index.php(45): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#28 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [path.public] does not exist. in E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php:805
Stack trace:
#0 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(681): Illuminate\Container\Container->build('path.public')
#1 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(785): Illuminate\Container\Container->resolve('path.public', Array, true)
#2 E:\www\test\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Foundation\Application->resolve('path.public', Array)
#3 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(770): Illuminate\Container\Container->make('path.public', Array)
#4 E:\www\test\vendor\october\rain\src\Foundation\Application.php(293): Illuminate\Foundation\Application->make('path.public')
#5 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(629): October\Rain\Foundation\Application->make('path.public')
#6 E:\www\test\vendor\october\rain\src\Filesystem\Filesystem.php(99): public_path()
#7 E:\www\test\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): October\Rain\Filesystem\Filesystem->localToPublic('E:\\www\\test\\...')
#8 E:\www\test\vendor\october\rain\src\Exception\ExceptionBase.php(233): Illuminate\Support\Facades\Facade::__callStatic('localToPublic', Array)
#9 E:\www\test\modules\system\views\exception.php(49): October\Rain\Exception\ExceptionBase->getCallStack()
#10 E:\www\test\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(43): include('E:\\www\\test\\...')
#11 E:\www\test\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(21): Illuminate\View\Engines\PhpEngine->evaluatePath('E:\\www\\test/...', Array)
#12 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(143): Illuminate\View\Engines\PhpEngine->get('E:\\www\\test/...', Array)
#13 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(126): Illuminate\View\View->getContents()
#14 E:\www\test\vendor\laravel\framework\src\Illuminate\View\View.php(91): Illuminate\View\View->renderContents()
#15 E:\www\test\vendor\laravel\framework\src\Illuminate\Http\Response.php(42): Illuminate\View\View->render()
#16 E:\www\test\vendor\symfony\http-foundation\Response.php(205): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#17 E:\www\test\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(55): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#18 E:\www\test\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(261): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500)
#19 E:\www\test\vendor\october\rain\src\Foundation\Exception\Handler.php(107): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#20 E:\www\test\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(101): October\Rain\Foundation\Exception\Handler->render(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#21 E:\www\test\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(69): Barryvdh\Debugbar\Middleware\InjectDebugbar->handleException(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#22 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 E:\www\test\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 E:\www\test\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#26 E:\www\test\index.php(45): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#27 {main}  
`````

**Comment by bennothommo** [comment]
@rajakhoury Please provide the Debug Bar plugin and October CMS versions you are using.

**Comment by rajakhoury** [comment]
Hi @bennothommo, sure please see the attached files. The oc db build is set to 470.

Were you able to reproduce this?

![plugins_version](https://user-images.githubusercontent.com/4506434/107354967-74126a00-6a94-11eb-8c44-cf433521fe52.png)
![composer](https://user-images.githubusercontent.com/4506434/107354972-770d5a80-6a94-11eb-9b7d-3b1d3b9c4920.png)

**Comment by daftspunk** [comment]
Moved to and fixed in https://github.com/octobercms/debugbar
