### ISSUE TITLE
Errors out on createAdmin install step

### ISSUE THREAD

**Issue by haydenbbickerton** [scottbedard/oc-debugbar-plugin#9]
Using a fresh copy of the oc installer, setting up from the oc project that I had added the debugbar plugin to. Everything goes smoothly, then fails when trying to create the admin. 

The ui throws this error - `A non well formed numeric value encountered`

The installer log has this:

```
[2016/05/15 12:17:01] Install step: createAdmin
[2016/05/15 05:17:01] Handler error (onInstallStep): A non well formed numeric value encountered
[2016/05/15 05:17:01] Trace log:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'A non well form...', '/var/www/html/o...', 332, Array)
#1 /var/www/html/october/plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php(332): Exception->__construct('Cannot add Mail...', '42S02', Object(Illuminate\Database\QueryException))
#2 /var/www/html/october/plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/ServiceProvider.php(111): Barryvdh\Debugbar\LaravelDebugbar->boot()
#3 [internal function]: Barryvdh\Debugbar\ServiceProvider->boot()
#4 /var/www/html/october/vendor/laravel/framework/src/Illuminate/Container/Container.php(526): call_user_func_array(Array, Array)
#5 /var/www/html/october/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(703): Illuminate\Container\Container->call(Array)
#6 /var/www/html/october/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(685): Illuminate\Foundation\Application->bootProvider(Object(Barryvdh\Debugbar\ServiceProvider))
#7 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Barryvdh\Debugbar\ServiceProvider), 20)
#8 /var/www/html/october/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): array_walk(Array, Object(Closure))
#9 /var/www/html/october/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
#10 /var/www/html/october/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(183): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(October\Rain\Foundation\Application))
#11 /var/www/html/october/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(195): Illuminate\Foundation\Application->bootstrapWith(Array)
#12 /var/www/html/october/install_files/php/Installer.php(674): Illuminate\Foundation\Console\Kernel->bootstrap()
#13 /var/www/html/october/install_files/php/Installer.php(503): Installer->bootFramework()
#14 /var/www/html/october/install_files/php/Installer.php(379): Installer->createAdminAccount()
#15 /var/www/html/october/install_files/php/Installer.php(48): Installer->onInstallStep()
#16 /var/www/html/october/install_files/php/boot.php(74): Installer->__construct()
#17 /var/www/html/october/install.php(1): include('/var/www/html/o...')
#18 {main}
```

Once I remove this plugin from the project and try again (with a fresh file and db setup), it works without a hitch.

**Comment by scottbedard** [comment]
Try attaching the debugbar plugin after you've installed October. I'm not sure why it's clobbering the installation process, and unfortunately I don't have much time to look into this.

**Comment by scottbedard** [comment]
Closing due to inactivity
